In [113]:
# import required libraries

In [114]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [115]:
# inlining of graphs

In [116]:
%matplotlib inline

In [117]:
# load dataset

In [118]:
df=pd.read_csv('./CleanupData.csv')
df

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes
5     Delhi  25.0        5800.0              Yes
6    Mumbai   NaN        5200.0               No
7     Delhi  38.0        7900.0              Yes
8  Banglore  40.0        8300.0               No
9     Delhi  27.0        6700.0              Yes

In [119]:
# get independent and dependent matrix
df.iloc[:,:-1]

State   Age  Pocket Money
0     Delhi  34.0        7200.0
1    Mumbai  17.0        4800.0
2  Banglore  20.0        5400.0
3    Mumbai  28.0        6100.0
4  Banglore  30.0           NaN
5     Delhi  25.0        5800.0
6    Mumbai   NaN        5200.0
7     Delhi  38.0        7900.0
8  Banglore  40.0        8300.0
9     Delhi  27.0        6700.0

In [120]:
X=df.iloc[:,:-1].values

In [121]:
# matrix of independent variables

In [122]:
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, nan],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', nan, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [123]:
# matrix of dependent variables

In [124]:
x=df.iloc[:,-1].values
x

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [125]:
# handle missing values

In [126]:
from sklearn.preprocessing import Imputer

In [127]:
imputer=Imputer(missing_values='NaN',strategy='mean')

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [128]:
imputer.fit(X[:,1:3])

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [129]:
X[:,1:3]=imputer.transform(X[:,1:3])

In [130]:
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, 6377.777777777777],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', 28.77777777777778, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [131]:
# handle categorical data

In [132]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X=LabelEncoder()

In [133]:
X[:,0]=labelencoder_X.fit_transform(X[:,0])
X

array([[1, 34.0, 7200.0],
       [2, 17.0, 4800.0],
       [0, 20.0, 5400.0],
       [2, 28.0, 6100.0],
       [0, 30.0, 6377.777777777777],
       [1, 25.0, 5800.0],
       [2, 28.77777777777778, 5200.0],
       [1, 38.0, 7900.0],
       [0, 40.0, 8300.0],
       [1, 27.0, 6700.0]], dtype=object)

In [134]:
# create dummy matrix for categorical dataset

In [135]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder=OneHotEncoder(categorical_features=[0])
X=onehotencoder.fit_transform(X).toarray()
np.set_printoptions(suppress=True)
X

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[   0.        ,    1.        ,    0.        ,   34.        ,
        7200.        ],
       [   0.        ,    0.        ,    1.        ,   17.        ,
        4800.        ],
       [   1.        ,    0.        ,    0.        ,   20.        ,
        5400.        ],
       [   0.        ,    0.        ,    1.        ,   28.        ,
        6100.        ],
       [   1.        ,    0.        ,    0.        ,   30.        ,
        6377.77777778],
       [   0.        ,    1.        ,    0.        ,   25.        ,
        5800.        ],
       [   0.        ,    0.        ,    1.        ,   28.77777778,
        5200.        ],
       [   0.        ,    1.        ,    0.        ,   38.        ,
        7900.        ],
       [   1.        ,    0.        ,    0.        ,   40.        ,
        8300.        ],
       [   0.        ,    1.        ,    0.        ,   27.        ,
        6700.        ]])

In [136]:
x

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [137]:
# handle dependent matrix x for categorical data

In [138]:
x=labelencoder_X.fit_transform(x)
x

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [139]:
# prepare test and training dataset

In [140]:
# Split data into 2 parts - training and test data

In [141]:
from sklearn.model_selection import train_test_split

In [142]:
Xtrn,Xtst,xtrn,xtst=train_test_split(X,x,test_size=0.2)

In [143]:
xtrn

array([0, 0, 0, 1, 1, 1, 0, 0])

In [144]:
Xtst

array([[   1.        ,    0.        ,    0.        ,   30.        ,
        6377.77777778],
       [   0.        ,    0.        ,    1.        ,   17.        ,
        4800.        ]])

In [145]:
Xtrn

array([[   1.        ,    0.        ,    0.        ,   20.        ,
        5400.        ],
       [   1.        ,    0.        ,    0.        ,   40.        ,
        8300.        ],
       [   0.        ,    0.        ,    1.        ,   28.77777778,
        5200.        ],
       [   0.        ,    1.        ,    0.        ,   25.        ,
        5800.        ],
       [   0.        ,    1.        ,    0.        ,   38.        ,
        7900.        ],
       [   0.        ,    1.        ,    0.        ,   27.        ,
        6700.        ],
       [   0.        ,    0.        ,    1.        ,   28.        ,
        6100.        ],
       [   0.        ,    1.        ,    0.        ,   34.        ,
        7200.        ]])

In [146]:
xtst

array([1, 1])

In [147]:
# Feature Scaling
# Standard Deviation and Normalization

In [148]:
from sklearn.preprocessing import StandardScaler

In [149]:
scale=StandardScaler()

In [150]:
Xtrn=scale.fit_transform(Xtrn)
Xtst=scale.transform(Xtst)

In [151]:
Xtrn

array([[ 1.73205081, -1.        , -0.57735027, -1.5979643 , -1.09361488],
       [ 1.73205081, -1.        , -0.57735027,  1.56719195,  1.60551972],
       [-0.57735027, -1.        ,  1.73205081, -0.20881239, -1.27976209],
       [-0.57735027,  1.        , -0.57735027, -0.80667524, -0.72132045],
       [-0.57735027,  1.        , -0.57735027,  1.25067632,  1.23322529],
       [-0.57735027,  1.        , -0.57735027, -0.49015961,  0.11634201],
       [-0.57735027, -1.        ,  1.73205081, -0.3319018 , -0.44209963],
       [-0.57735027,  1.        , -0.57735027,  0.61764507,  0.58171004]])

In [152]:
Xtst

array([[ 1.73205081, -1.        , -0.57735027, -0.01538618, -0.18356184],
       [-0.57735027, -1.        ,  1.73205081, -2.07273774, -1.65205652]])

In [153]:
# Now this dataset is completely ready to be fetched into ML algorithms